# teste1
name: bike_automacao
run-name: ${{ github.actor }} Pipeline deploy :)
on:
  push:
    branches:
      - "main"
    paths:
      - images/**
      - .github/workflows/main.yml
jobs:
  githubactions-bike:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar SSH
        run: sudo apt-get install -y ssh openssh-client

      - name: Adicionar EC2 ao known-hosts
        run: |
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''
          ssh-keyscan -H 35.153.179.210 >> ~/.ssh/known_hosts

      - name: Verificar a chave
        run: echo "$SSH_PRIVATE_KEY"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}

      - name: Copiar imagens para maquina remota
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key.pem

          chmod 600 ssh_key.pem
          scp -i ssh_key.pem images/* ec2-user@35.153.179.210:/home/ec2-user/efs
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
